import { writeFileSync } from 'fs';
import { expect, test } from '@playwright/test';
import { loadWorkspaceCatalog } from '../lib/application/catalog';
import { projectInterfaceIntelligence } from '../lib/application/interface-intelligence';
import { SchemaError } from '../lib/domain/errors';
import { validateBehaviorPatternDocument } from '../lib/domain/validation';
import { runWithLocalServices } from '../lib/composition/local-services';
import { createTestWorkspace } from './support/workspace';

test('behavior pattern validation requires effect assertions', () => {
  expect(() => validateBehaviorPatternDocument({
    kind: 'behavior-pattern',
    version: 1,
    id: 'core.invalid.behavior',
    aliases: [],
    stateNodes: [{
      ref: 'state:policy-search:invalid-hidden',
      screen: 'policy-search',
      label: 'Invalid state hidden',
      aliases: [],
      scope: 'target',
      targetRef: 'target:element:policy-search:validationSummary',
      routeVariantRefs: [],
      predicates: [{ kind: 'hidden', targetRef: 'target:element:policy-search:validationSummary' }],
      provenance: [],
    }],
    eventSignatures: [{
      ref: 'event:policy-search:invalid-hide-validation',
      screen: 'policy-search',
      targetRef: 'target:element:policy-search:policyNumberInput',
      label: 'Hide validation with input',
      aliases: [],
      dispatch: { action: 'input', sampleValue: 'POL-001' },
      requiredStateRefs: [],
      forbiddenStateRefs: [],
      effects: {
        transitionRefs: ['transition:policy-search:invalid-hide-validation'],
        resultStateRefs: ['state:policy-search:invalid-hidden'],
        observableEffects: ['validation-cleared'],
        assertions: [],
      },
      observationPlan: {
        timeoutMs: 1500,
        settleMs: 50,
        observeStateRefs: ['state:policy-search:invalid-hidden'],
      },
      provenance: [],
    }],
    transitions: [{
      ref: 'transition:policy-search:invalid-hide-validation',
      screen: 'policy-search',
      label: 'Hide validation',
      aliases: [],
      eventSignatureRef: 'event:policy-search:invalid-hide-validation',
      sourceStateRefs: [],
      targetStateRefs: ['state:policy-search:invalid-hidden'],
      effectKind: 'hide',
      observableEffects: ['validation-cleared'],
      provenance: [],
    }],
  })).toThrowError(SchemaError);
});

test('interface projection rejects duplicate transition semantics under different refs', async () => {
  const workspace = createTestWorkspace('phase2-duplicate-transition');
  try {
    writeFileSync(
      workspace.suiteResolve('knowledge', 'patterns', 'duplicate-transition.behavior.yaml'),
      [
        'kind: behavior-pattern',
        'version: 1',
        'id: core.duplicate.transition',
        'aliases: []',
        'stateNodes:',
        '  - ref: state:policy-search:policy-number-cleared',
        '    screen: policy-search',
        '    label: Policy number field is cleared',
        '    aliases:',
        '      - policy number empty',
        '      - search field empty',
        '    scope: target',
        '    targetRef: target:element:policy-search:policyNumberInput',
        '    routeVariantRefs:',
        '      - route-variant:demo:policy-search:default',
        '    predicates:',
        '      - kind: cleared',
        '        targetRef: target:element:policy-search:policyNumberInput',
        '        attribute: value',
        '        value: ""',
        '    provenance: []',
        '  - ref: state:policy-search:policy-number-populated',
        '    screen: policy-search',
        '    label: Policy number field is populated',
        '    aliases:',
        '      - policy number entered',
        '      - policy number populated',
        '      - policy ref entered',
        '    scope: target',
        '    targetRef: target:element:policy-search:policyNumberInput',
        '    routeVariantRefs:',
        '      - route-variant:demo:policy-search:default',
        '      - route-variant:demo:policy-search:results-with-policy',
        '    predicates:',
        '      - kind: populated',
        '        targetRef: target:element:policy-search:policyNumberInput',
        '        attribute: value',
        '    provenance: []',
        '  - ref: state:policy-search:validation-hidden',
        '    screen: policy-search',
        '    label: Validation summary is hidden',
        '    aliases:',
        '      - validation hidden',
        '      - no validation summary shown',
        '    scope: target',
        '    targetRef: target:element:policy-search:validationSummary',
        '    routeVariantRefs:',
        '      - route-variant:demo:policy-search:default',
        '      - route-variant:demo:policy-search:results-with-policy',
        '    predicates:',
        '      - kind: hidden',
        '        targetRef: target:element:policy-search:validationSummary',
        '    provenance: []',
        'eventSignatures:',
        '  - ref: event:policy-search:enter-policy-number',
        '    screen: policy-search',
        '    targetRef: target:element:policy-search:policyNumberInput',
        '    label: Enter policy number',
        '    aliases:',
        '      - enter policy number',
        '      - enter policy number in search field',
        '      - enter policy ref',
        '    dispatch:',
        '      action: input',
        '      sampleValue: POL-001',
        '    requiredStateRefs: []',
        '    forbiddenStateRefs: []',
        '    effects:',
        '      transitionRefs:',
        '        - transition:policy-search:populate-policy-number-duplicate',
        '      resultStateRefs:',
        '        - state:policy-search:policy-number-populated',
        '      observableEffects:',
        '        - value-entry',
        '      assertions:',
        '        - Policy number field keeps the entered value',
        '    observationPlan:',
        '      timeoutMs: 1500',
        '      settleMs: 50',
        '      observeStateRefs:',
        '        - state:policy-search:policy-number-populated',
        '    provenance: []',
        'transitions:',
        '  - ref: transition:policy-search:populate-policy-number-duplicate',
        '    screen: policy-search',
        '    label: Duplicate policy number population',
        '    aliases: []',
        '    eventSignatureRef: event:policy-search:enter-policy-number',
        '    sourceStateRefs:',
        '      - state:policy-search:policy-number-cleared',
        '    targetStateRefs:',
        '      - state:policy-search:policy-number-populated',
        '    effectKind: populate',
        '    observableEffects:',
        '      - value-entry',
        '    provenance: []',
      ].join('\n'),
      'utf8',
    );

    await expect(async () => {
      const catalog = await runWithLocalServices(loadWorkspaceCatalog({ paths: workspace.paths }), workspace.rootDir);
      await runWithLocalServices(projectInterfaceIntelligence({ paths: workspace.paths, catalog }), workspace.rootDir);
    }).rejects.toThrow(/duplicate transition semantics/i);
  } finally {
    workspace.cleanup();
  }
});

test('interface projection rejects support cycles in event prerequisites', async () => {
  const workspace = createTestWorkspace('phase2-support-cycle');
  try {
    writeFileSync(
      workspace.suiteResolve('knowledge', 'patterns', 'support-cycle.behavior.yaml'),
      [
        'kind: behavior-pattern',
        'version: 1',
        'id: core.support-cycle',
        'aliases: []',
        'stateNodes:',
        '  - ref: state:policy-search:cycle-a',
        '    screen: policy-search',
        '    label: Cycle A',
        '    aliases: []',
        '    scope: target',
        '    targetRef: target:element:policy-search:searchButton',
        '    routeVariantRefs: []',
        '    predicates:',
        '      - kind: visible',
        '        targetRef: target:element:policy-search:searchButton',
        '    provenance: []',
        '  - ref: state:policy-search:cycle-b',
        '    screen: policy-search',
        '    label: Cycle B',
        '    aliases: []',
        '    scope: target',
        '    targetRef: target:element:policy-search:searchButton',
        '    routeVariantRefs: []',
        '    predicates:',
        '      - kind: hidden',
        '        targetRef: target:element:policy-search:searchButton',
        '    provenance: []',
        'eventSignatures:',
        '  - ref: event:policy-search:cycle-a',
        '    screen: policy-search',
        '    targetRef: target:element:policy-search:searchButton',
        '    label: Reach Cycle A',
        '    aliases: []',
        '    dispatch:',
        '      action: click',
        '    requiredStateRefs:',
        '      - state:policy-search:cycle-b',
        '    forbiddenStateRefs: []',
        '    effects:',
        '      transitionRefs:',
        '        - transition:policy-search:cycle-a',
        '      resultStateRefs:',
        '        - state:policy-search:cycle-a',
        '      observableEffects:',
        '        - cycle-a-visible',
        '      assertions:',
        '        - Cycle A becomes observable',
        '    observationPlan:',
        '      timeoutMs: 500',
        '      settleMs: 0',
        '      observeStateRefs:',
        '        - state:policy-search:cycle-a',
        '  - ref: event:policy-search:cycle-b',
        '    screen: policy-search',
        '    targetRef: target:element:policy-search:searchButton',
        '    label: Reach Cycle B',
        '    aliases: []',
        '    dispatch:',
        '      action: click',
        '    requiredStateRefs:',
        '      - state:policy-search:cycle-a',
        '    forbiddenStateRefs: []',
        '    effects:',
        '      transitionRefs:',
        '        - transition:policy-search:cycle-b',
        '      resultStateRefs:',
        '        - state:policy-search:cycle-b',
        '      observableEffects:',
        '        - cycle-b-visible',
        '      assertions:',
        '        - Cycle B becomes observable',
        '    observationPlan:',
        '      timeoutMs: 500',
        '      settleMs: 0',
        '      observeStateRefs:',
        '        - state:policy-search:cycle-b',
        'transitions:',
        '  - ref: transition:policy-search:cycle-a',
        '    screen: policy-search',
        '    label: Transition to Cycle A',
        '    aliases: []',
        '    eventSignatureRef: event:policy-search:cycle-a',
        '    sourceStateRefs: []',
        '    targetStateRefs:',
        '      - state:policy-search:cycle-a',
        '    effectKind: reveal',
        '    observableEffects:',
        '      - cycle-a-visible',
        '    provenance: []',
        '  - ref: transition:policy-search:cycle-b',
        '    screen: policy-search',
        '    label: Transition to Cycle B',
        '    aliases: []',
        '    eventSignatureRef: event:policy-search:cycle-b',
        '    sourceStateRefs: []',
        '    targetStateRefs:',
        '      - state:policy-search:cycle-b',
        '    effectKind: reveal',
        '    observableEffects:',
        '      - cycle-b-visible',
        '    provenance: []',
      ].join('\n'),
      'utf8',
    );

    await expect(async () => {
      const catalog = await runWithLocalServices(loadWorkspaceCatalog({ paths: workspace.paths }), workspace.rootDir);
      await runWithLocalServices(projectInterfaceIntelligence({ paths: workspace.paths, catalog }), workspace.rootDir);
    }).rejects.toThrow(/support cycle detected/i);
  } finally {
    workspace.cleanup();
  }
});
