import * as ts from 'typescript';

const printer = ts.createPrinter({
  newLine: ts.NewLineKind.LineFeed,
});

const GENERATED_BANNER = ' AUTO-GENERATED by tesseract -- do not hand-edit';

function isSimpleIdentifier(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

export function identifier(name: string): ts.Identifier {
  return ts.factory.createIdentifier(name);
}

export function stringLiteral(value: string): ts.StringLiteral {
  return ts.factory.createStringLiteral(value);
}

export function asConst(expression: ts.Expression): ts.AsExpression {
  return ts.factory.createAsExpression(expression, ts.factory.createTypeReferenceNode('const'));
}

export function expressionFromLiteral(value: unknown): ts.Expression {
  if (value === null) {
    return ts.factory.createNull();
  }

  if (value === undefined) {
    return identifier('undefined');
  }

  if (Array.isArray(value)) {
    return ts.factory.createArrayLiteralExpression(value.map((entry) => expressionFromLiteral(entry)), true);
  }

  switch (typeof value) {
    case 'boolean':
      return value ? ts.factory.createTrue() : ts.factory.createFalse();
    case 'number':
      return ts.factory.createNumericLiteral(value);
    case 'string':
      return stringLiteral(value);
    case 'object':
      return ts.factory.createObjectLiteralExpression(
        Object.entries(value as Record<string, unknown>).map(([key, entryValue]) =>
          ts.factory.createPropertyAssignment(
            isSimpleIdentifier(key) ? identifier(key) : stringLiteral(key),
            expressionFromLiteral(entryValue),
          ),
        ),
        true,
      );
    default:
      return stringLiteral(String(value));
  }
}

export function property(base: ts.Expression, name: string): ts.Expression {
  return isSimpleIdentifier(name)
    ? ts.factory.createPropertyAccessExpression(base, identifier(name))
    : ts.factory.createElementAccessExpression(base, stringLiteral(name));
}

export function propertyChain(base: ts.Expression, ...segments: string[]): ts.Expression {
  return segments.reduce((current, segment) => property(current, segment), base);
}

export function callExpression(callee: ts.Expression, args: ts.Expression[]): ts.CallExpression {
  return ts.factory.createCallExpression(callee, undefined, args);
}

export function awaitExpression(expression: ts.Expression): ts.AwaitExpression {
  return ts.factory.createAwaitExpression(expression);
}

export function statementFromExpression(expression: ts.Expression): ts.ExpressionStatement {
  return ts.factory.createExpressionStatement(expression);
}

export function constStatement(name: string, initializer: ts.Expression, isExported = false): ts.VariableStatement {
  return ts.factory.createVariableStatement(
    isExported ? [ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)] : undefined,
    ts.factory.createVariableDeclarationList(
      [ts.factory.createVariableDeclaration(identifier(name), undefined, undefined, initializer)],
      ts.NodeFlags.Const,
    ),
  );
}

export function typeAliasStatement(
  name: string,
  type: ts.TypeNode,
  options?: { exported?: boolean; parameters?: ts.TypeParameterDeclaration[] },
): ts.TypeAliasDeclaration {
  return ts.factory.createTypeAliasDeclaration(
    options?.exported ? [ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)] : undefined,
    identifier(name),
    options?.parameters,
    type,
  );
}

export function importDeclaration(options: {
  modulePath: string;
  defaultImport?: string;
  namedImports?: string[];
}): ts.ImportDeclaration {
  const defaultImport = options.defaultImport ? identifier(options.defaultImport) : undefined;
  const namedImports = options.namedImports && options.namedImports.length > 0
    ? ts.factory.createNamedImports(options.namedImports.map((name) => ts.factory.createImportSpecifier(false, undefined, identifier(name))))
    : undefined;
  const importClause = ts.factory.createImportClause(false, defaultImport, namedImports);
  return ts.factory.createImportDeclaration(undefined, importClause, stringLiteral(options.modulePath));
}

export function objectBindingPattern(names: string[]): ts.ObjectBindingPattern {
  return ts.factory.createObjectBindingPattern(
    names.map((name) => ts.factory.createBindingElement(undefined, undefined, identifier(name), undefined)),
  );
}

export function unionOfStringLiterals(values: string[]): ts.TypeNode {
  if (values.length === 0) {
    return ts.factory.createKeywordTypeNode(ts.SyntaxKind.NeverKeyword);
  }

  const literals = values.map((value) => ts.factory.createLiteralTypeNode(stringLiteral(value)));
  return literals.length === 1 ? literals[0] : ts.factory.createUnionTypeNode(literals);
}

export function conditionalByScreen(
  parameterName: string,
  cases: Array<{ screen: string; values: string[] }>,
): ts.TypeNode {
  return [...cases].reverse().reduce<ts.TypeNode>(
    (fallback, entry) =>
      ts.factory.createConditionalTypeNode(
        ts.factory.createTypeReferenceNode(parameterName),
        ts.factory.createLiteralTypeNode(stringLiteral(entry.screen)),
        unionOfStringLiterals(entry.values),
        fallback,
      ),
    ts.factory.createKeywordTypeNode(ts.SyntaxKind.NeverKeyword),
  );
}

export function printModule(statements: ts.Statement[]): string {
  const sourceFile = ts.createSourceFile('generated.ts', '', ts.ScriptTarget.Latest, false, ts.ScriptKind.TS);
  const body = statements.map((statement, index) => {
    if (index !== 0) {
      return statement;
    }
    return ts.addSyntheticLeadingComment(statement, ts.SyntaxKind.SingleLineCommentTrivia, GENERATED_BANNER, true);
  });
  return `${printer.printList(ts.ListFormat.MultiLine, ts.factory.createNodeArray(body), sourceFile)}\n`;
}

