export const artifactValidationKinds = [
  'ado-snapshot',
  'scenario',
  'bound-scenario',
  'scenario-interpretation-surface',
  'scenario-task-packet',
  'run-record',
  'proposal-bundle',
  'surface-graph',
  'screen-elements',
  'screen-hints',
  'dataset-control',
  'resolution-control',
  'runbook-control',
  'pattern-document',
  'shared-patterns',
  'screen-postures',
  'screen-behavior',
  'behavior-pattern-document',
  'manifest',
  'derived-graph',
  'trust-policy',
  'trust-policy-evaluation',
  'operator-inbox-item',
  'approval-receipt',
  'rerun-plan',
  'confidence-overlay-catalog',
  'benchmark-context',
  'resolution-graph-record',
  'interpretation-drift-record',
  'benchmark-scorecard',
  'benchmark-improvement-projection',
  'dogfood-run',
] as const;

export type ArtifactValidationKind = (typeof artifactValidationKinds)[number];
